DROP TABLE episodes;
DROP TABLE episodeIV;

-- For Episode IV

CREATE TABLE episodeIV (name STRING, line STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");
LOAD DATA LOCAl INPATH '/root/inputs/episodeIV_dialogues.txt' INTO TABLE episodeIV;

INSERT OVERWRITE LOCAL DIRECTORY '/root/HiveOutput2'
SELECT COUNT(*) FROM episodeIV WHERE INSTR(line, 'Luke')>0;